# filepath: /Users/anuragmaurya/Documents/Coding/projects/thumbnaily/docker-compose.yml
services:
  postgres:
    image: postgres
    volumes:
      - dbvol:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
  
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  
  web:
    build:
      context: ./
      dockerfile: docker/Dockerfile.web
      target: development
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/thumbnaily
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules
      - /app/apps/web/.next
  
  worker:
    build:
      context: ./
      dockerfile: docker/Dockerfile.worker
      target: development
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/thumbnaily
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./apps/worker:/app/apps/worker
      - /app/apps/worker/node_modules
      - /app/apps/worker/dist

volumes:
  dbvol:
  redis-data: